### ISSUE TITLE
ModuleNotFoundError: No module named 'csdecoder' (Debian)

### ISSUE THREAD

**Issue by InnovativeInventor** [colorsafe/colorsafe#3] opened 2017-12-21 21:44 UTC
I'm not sure whats happening, but for some reason when I type `colorsafe encode test.png`

I get:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/colorsafe", line 11, in <module>
    load_entry_point('colorsafe==0.1.0.dev4', 'console_scripts', 'colorsafe')()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/colorsafe/cmd.py", line 3, in <module>
    from csdecoder import ColorSafeDecoder
ModuleNotFoundError: No module named 'csdecoder'
```

**Comment by Wikinaut** [comment] 2018-05-10 01:49
Same for me.

@justinbass Pls. can you assist?

**Comment by Wikinaut** [comment] 2018-05-10 02:02
@InnovativeInventor Could you solve your problem, how?

**Comment by justinbass** [comment] 2018-05-10 06:25
This only works for Python 2 currently. Originally this was by design, since the program is supposed to be archival by nature. But since Python 2 is being outright deprecated slowly in favor of Python 3 I've since changed my mind.

**Comment by Wikinaut** [comment] 2018-05-10 07:40
uh, pls. can you fix this so that I can start testing your code?

**Comment by justinbass** [comment] 2018-05-10 21:16
The fix is to use Python 2. I don't need you to test this - it's in an early stage, and I am aware of its issues and how to proceed. What I need, unfortunately, is more free time...

**Comment by Wikinaut** [comment] 2018-05-11 00:18
In that way I cannot test your code on my debian 9 and 10 systems, and the bounty (from May 2015) decision https://github.com/Rupan/paperbak/issues/1 has to be further postponed.

For your information, I just upgraded to debian 10 and there we have

```
$ python --version
Python 2.7.15

$ python3 --version
Python 3.6.5rc1
```

**Comment by justinbass** [comment] 2018-05-11 22:16
I have not tried on Debian, but tested this on Ubuntu, macOS, and Windows via Cygwin. I'm using pip install colorsafe, and it's working out of the box. Can you provide more details in how you're setting it up?

**Comment by Wikinaut** [comment] 2018-05-11 23:10
```pip install colorsafe```

**Comment by justinbass** [comment] 2018-05-12 05:35
This is working more or less for me on Debian 9, though pip is broken out of the box and requires some modification: https://github.com/pypa/pip/issues/5221. Not sure what you are seeing, but I'm not able to replicate it. Please try again on a different operating system if possible.

**Comment by justinbass** [comment] 2018-05-13 03:01
Also working on Raspbian Wheezy out of the box. If you have more information let me know, but I only intend to support this for the most common operating systems.

**Comment by Wikinaut** [comment] 2018-05-13 03:57
and the bounty can only be paid if I am satisfied.

**Comment by justinbass** [comment] 2018-05-13 04:40
As mentioned previously, I would only accept payment in the form of a donation to the Free Software Foundation or other similar cause. I'd advise giving the bounty to the author of paperback-cli, who seems to have satisfied the original intention of your bounty requirements more closely.

I'll close this ticket out for now. Please re-open (with full information) if you notice an issue elsewhere.

**Closed by justinbass** 2018-05-13 04:40 UTC
